name: Publish Skeleton
on:
  push:
    branches:
      - dev
    paths:
      - ".changeset/**"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Packaging
        run: |
          pnpm package
          cd package
          pnpm publish --tag dev
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
