name: Publish Skeleton
on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run prettier and eslint
        run: pnpm ci:lint
      
      - name: Run svelte-check
        run: pnpm ci:check
        
  release:
    name: Release
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use PNPM v8
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "chore(release): version package"
          title: "chore(release): version package"
          publish: pnpm ci:release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge master into dev on publish
        if: steps.changesets.outputs.published == 'true'
        run: |
          git checkout dev
          git merge master
          git push
      
      - name: Deploy master to Vercel
        if: steps.changesets.outputs.published == 'true'
        run: |
          git checkout dev
          git merge master
          git push
