name: Publish Skeleton
on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:     
  release:
    name: Build & Publish latest Release
    if: github.repository == 'AdrianGonz97/experimental-skeleton-monorepo'
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use PNPM v8
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # PNPM Store cache setup
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "chore(release): version package"
          title: "chore(release): version package"
          publish: pnpm ci:release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge master into dev on publish
        if: steps.changesets.outputs.published == 'true'
        run: |
          git add ./packages/skeleton/scripts/tw-settings.json
          git commit -m "updated tw-settings.json"
          git push
          git checkout dev
          git merge master
          git push
